import playfunction as pf


def main():
    pf.playNote("F4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
   
    pf.playNote("A4", "quarter", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("Bb4", "quarter", 96, "sine")
   
    pf.playNote("A4", "quarter", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("G4", "quarter", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    
    pf.playNote("E4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("F4", "half", 96, "sine")
    pf.playNote("F4", "quarter", 96, "sine")
    
    pf.playNote("C5", "quarter", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    
    pf.playNote("C5", "quarter", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("B4", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("C5", "quarter", 96, "sine")
    
    pf.playNote("Bb4", "quarter", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("Bb4", "quarter", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("A4", "half_pointed", 96, "sine")
    
    pf.playNote("A4", "quarter", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "quarter", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("Bb4", "quarter", 96, "sine")
    pf.playNote("Bb4", "quarter", 96, "sine")
    
    pf.playNote("A4", "quarter", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("G4", "quarter", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    
    pf.playNote("E4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("F4", "half_pointed", 96, "sine")
    
    pf.playNote("A3", "eighth", 96, "sine")
    pf.playNote("A3", "eighth", 96, "sine")
    pf.playNote("A3", "eighth", 96, "sine")
    pf.playNote("A3", "eighth", 96, "sine")
    pf.playNote("A3", "quarter", 96, "sine")
    pf.playNote("A3", "eighth", 96, "sine")
    pf.playNote("Bb3", "eighth", 96, "sine")
    
    pf.playNote("G3", "eighth", 96, "sine")
    pf.playNote("A3", "eighth", 96, "sine")
    pf.playNote("Bb3", "half_pointed", 96, "sine")
    
    pf.playNote("A3", "eighth", 96, "sine")
    pf.playNote("Bb3", "eighth", 96, "sine")
    pf.playNote("C4", "eighth", 96, "sine")
    pf.playNote("C4", "eighth", 96, "sine")
    pf.playNote("C4", "quarter", 96, "sine")
    pf.playNote("Bb3", "eighth", 96, "sine")
    pf.playNote("A3", "eighth", 96, "sine")
    
    pf.playNote("G3", "eighth", 96, "sine")
    pf.playNote("Bb3", "eighth", 96, "sine")
    pf.playNote("A3", "half_pointed", 96, "sine")
    
    pf.playNote("A3", "quarter", 96, "sine")
    pf.playNote("A3", "quarter", 96, "sine")
    pf.playNote("G3", "eighth", 96, "sine")
    pf.playNote("G3", "eighth", 96, "sine")
    pf.playNote("G3", "eighth", 96, "sine")
    pf.playNote("G3", "eighth", 96, "sine")
    
    pf.playNote("E3", "eighth", 96, "sine")
    pf.playNote("G3", "eighth", 96, "sine")
    pf.playNote("F3", "half_pointed", 96, "sine")
    
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "quarter", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("B4", "eighth", 96, "sine")
    
    pf.playNote("C5", "quarter", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("B4", "eighth", 96, "sine")
    pf.playNote("D5", "eighth", 96, "sine")
    pf.playNote("C5", "quarter", 96, "sine")
    
    pf.playNote("Bb4", "quarter", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("A4", "quarter", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "sixteenth", 96, "sine")
    pf.playNote("Bb4", "sixteenth", 96, "sine")
    
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("Bb4", "eighth", 96, "sine")
    pf.playNote("A4", "half", 96, "sine")
    pf.playNote("E5", "eighth", 96, "sine")
    pf.playNote("E5", "eighth", 96, "sine")
    
    pf.playNote("F5", "half_pointed", 96, "sine")
    pf.playNote("E5", "eighth", 96, "sine")
    pf.playNote("D5", "eighth", 96, "sine")
    
    pf.playNote("E5", "half_pointed", 96, "sine")
    pf.playNote("C5", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    
    pf.playNote("D5", "full", 96, "sine")
    
    pf.playNote("F4", "eighth", 96, "sine")
    pf.playNote("F4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    pf.playNote("G4", "eighth", 96, "sine")
    pf.playNote("A4", "eighth", 96, "sine")
    
    pf.playNote("Bb4", "full", 96, "sine")

if __name__ == '__main__':
    main()
